/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RemoveBackgroundRouteImport } from './routes/remove-background'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PdfToImageRouteImport } from './routes/pdf-to-image'
import { Route as KbResizePixelRouteImport } from './routes/kb-resize-pixel'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsUnitConverterRouteImport } from './routes/tools.unit-converter'
import { Route as ToolsTimeZoneConverterRouteImport } from './routes/tools.time-zone-converter'
import { Route as ToolsTextOnPhotoRouteImport } from './routes/tools.text-on-photo'
import { Route as ToolsSipCalculatorRouteImport } from './routes/tools.sip-calculator'
import { Route as ToolsRemoveBackgroundRouteImport } from './routes/tools.remove-background'
import { Route as ToolsQrGeneratorRouteImport } from './routes/tools.qr-generator'
import { Route as ToolsPpfCalculatorRouteImport } from './routes/tools.ppf-calculator'
import { Route as ToolsPincodeLookupRouteImport } from './routes/tools.pincode-lookup'
import { Route as ToolsPdfToImageRouteImport } from './routes/tools.pdf-to-image'
import { Route as ToolsNumberConverterRouteImport } from './routes/tools.number-converter'
import { Route as ToolsMortgageCalculatorRouteImport } from './routes/tools.mortgage-calculator'
import { Route as ToolsLoanEmiCalculatorRouteImport } from './routes/tools.loan-emi-calculator'
import { Route as ToolsKbConverterRouteImport } from './routes/tools.kb-converter'
import { Route as ToolsImageToPdfRouteImport } from './routes/tools.image-to-pdf'
import { Route as ToolsImageCropperRouteImport } from './routes/tools.image-cropper'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools.image-compressor'
import { Route as ToolsFdCalculatorRouteImport } from './routes/tools.fd-calculator'
import { Route as ToolsEtsyFeeCalculatorRouteImport } from './routes/tools.etsy-fee-calculator'
import { Route as ToolsCurrencyConverterRouteImport } from './routes/tools.currency-converter'
import { Route as ToolsCryptoConverterRouteImport } from './routes/tools.crypto-converter'
import { Route as ToolsColorPickerRouteImport } from './routes/tools.color-picker'
import { Route as ToolsBmiCalculatorRouteImport } from './routes/tools.bmi-calculator'
import { Route as ToolsAgeCalculatorRouteImport } from './routes/tools.age-calculator'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoveBackgroundRoute = RemoveBackgroundRouteImport.update({
  id: '/remove-background',
  path: '/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToImageRoute = PdfToImageRouteImport.update({
  id: '/pdf-to-image',
  path: '/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const KbResizePixelRoute = KbResizePixelRouteImport.update({
  id: '/kb-resize-pixel',
  path: '/kb-resize-pixel',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUnitConverterRoute = ToolsUnitConverterRouteImport.update({
  id: '/tools/unit-converter',
  path: '/tools/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTimeZoneConverterRoute = ToolsTimeZoneConverterRouteImport.update({
  id: '/tools/time-zone-converter',
  path: '/tools/time-zone-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTextOnPhotoRoute = ToolsTextOnPhotoRouteImport.update({
  id: '/tools/text-on-photo',
  path: '/tools/text-on-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSipCalculatorRoute = ToolsSipCalculatorRouteImport.update({
  id: '/tools/sip-calculator',
  path: '/tools/sip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRemoveBackgroundRoute = ToolsRemoveBackgroundRouteImport.update({
  id: '/tools/remove-background',
  path: '/tools/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrGeneratorRoute = ToolsQrGeneratorRouteImport.update({
  id: '/tools/qr-generator',
  path: '/tools/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPpfCalculatorRoute = ToolsPpfCalculatorRouteImport.update({
  id: '/tools/ppf-calculator',
  path: '/tools/ppf-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPincodeLookupRoute = ToolsPincodeLookupRouteImport.update({
  id: '/tools/pincode-lookup',
  path: '/tools/pincode-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToImageRoute = ToolsPdfToImageRouteImport.update({
  id: '/tools/pdf-to-image',
  path: '/tools/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNumberConverterRoute = ToolsNumberConverterRouteImport.update({
  id: '/tools/number-converter',
  path: '/tools/number-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMortgageCalculatorRoute = ToolsMortgageCalculatorRouteImport.update({
  id: '/tools/mortgage-calculator',
  path: '/tools/mortgage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoanEmiCalculatorRoute = ToolsLoanEmiCalculatorRouteImport.update({
  id: '/tools/loan-emi-calculator',
  path: '/tools/loan-emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsKbConverterRoute = ToolsKbConverterRouteImport.update({
  id: '/tools/kb-converter',
  path: '/tools/kb-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageToPdfRoute = ToolsImageToPdfRouteImport.update({
  id: '/tools/image-to-pdf',
  path: '/tools/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCropperRoute = ToolsImageCropperRouteImport.update({
  id: '/tools/image-cropper',
  path: '/tools/image-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFdCalculatorRoute = ToolsFdCalculatorRouteImport.update({
  id: '/tools/fd-calculator',
  path: '/tools/fd-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEtsyFeeCalculatorRoute = ToolsEtsyFeeCalculatorRouteImport.update({
  id: '/tools/etsy-fee-calculator',
  path: '/tools/etsy-fee-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCurrencyConverterRoute = ToolsCurrencyConverterRouteImport.update({
  id: '/tools/currency-converter',
  path: '/tools/currency-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCryptoConverterRoute = ToolsCryptoConverterRouteImport.update({
  id: '/tools/crypto-converter',
  path: '/tools/crypto-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorPickerRoute = ToolsColorPickerRouteImport.update({
  id: '/tools/color-picker',
  path: '/tools/color-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBmiCalculatorRoute = ToolsBmiCalculatorRouteImport.update({
  id: '/tools/bmi-calculator',
  path: '/tools/bmi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAgeCalculatorRoute = ToolsAgeCalculatorRouteImport.update({
  id: '/tools/age-calculator',
  path: '/tools/age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/kb-resize-pixel': typeof KbResizePixelRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/privacy': typeof PrivacyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/remove-background': typeof RemoveBackgroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/color-picker': typeof ToolsColorPickerRoute
  '/tools/crypto-converter': typeof ToolsCryptoConverterRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/etsy-fee-calculator': typeof ToolsEtsyFeeCalculatorRoute
  '/tools/fd-calculator': typeof ToolsFdCalculatorRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-cropper': typeof ToolsImageCropperRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/kb-converter': typeof ToolsKbConverterRoute
  '/tools/loan-emi-calculator': typeof ToolsLoanEmiCalculatorRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/number-converter': typeof ToolsNumberConverterRoute
  '/tools/pdf-to-image': typeof ToolsPdfToImageRoute
  '/tools/pincode-lookup': typeof ToolsPincodeLookupRoute
  '/tools/ppf-calculator': typeof ToolsPpfCalculatorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/remove-background': typeof ToolsRemoveBackgroundRoute
  '/tools/sip-calculator': typeof ToolsSipCalculatorRoute
  '/tools/text-on-photo': typeof ToolsTextOnPhotoRoute
  '/tools/time-zone-converter': typeof ToolsTimeZoneConverterRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/kb-resize-pixel': typeof KbResizePixelRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/privacy': typeof PrivacyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/remove-background': typeof RemoveBackgroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/color-picker': typeof ToolsColorPickerRoute
  '/tools/crypto-converter': typeof ToolsCryptoConverterRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/etsy-fee-calculator': typeof ToolsEtsyFeeCalculatorRoute
  '/tools/fd-calculator': typeof ToolsFdCalculatorRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-cropper': typeof ToolsImageCropperRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/kb-converter': typeof ToolsKbConverterRoute
  '/tools/loan-emi-calculator': typeof ToolsLoanEmiCalculatorRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/number-converter': typeof ToolsNumberConverterRoute
  '/tools/pdf-to-image': typeof ToolsPdfToImageRoute
  '/tools/pincode-lookup': typeof ToolsPincodeLookupRoute
  '/tools/ppf-calculator': typeof ToolsPpfCalculatorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/remove-background': typeof ToolsRemoveBackgroundRoute
  '/tools/sip-calculator': typeof ToolsSipCalculatorRoute
  '/tools/text-on-photo': typeof ToolsTextOnPhotoRoute
  '/tools/time-zone-converter': typeof ToolsTimeZoneConverterRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-to-pdf': typeof ImageToPdfRoute
  '/kb-resize-pixel': typeof KbResizePixelRoute
  '/pdf-to-image': typeof PdfToImageRoute
  '/privacy': typeof PrivacyRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/remove-background': typeof RemoveBackgroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/color-picker': typeof ToolsColorPickerRoute
  '/tools/crypto-converter': typeof ToolsCryptoConverterRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/etsy-fee-calculator': typeof ToolsEtsyFeeCalculatorRoute
  '/tools/fd-calculator': typeof ToolsFdCalculatorRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-cropper': typeof ToolsImageCropperRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/kb-converter': typeof ToolsKbConverterRoute
  '/tools/loan-emi-calculator': typeof ToolsLoanEmiCalculatorRoute
  '/tools/mortgage-calculator': typeof ToolsMortgageCalculatorRoute
  '/tools/number-converter': typeof ToolsNumberConverterRoute
  '/tools/pdf-to-image': typeof ToolsPdfToImageRoute
  '/tools/pincode-lookup': typeof ToolsPincodeLookupRoute
  '/tools/ppf-calculator': typeof ToolsPpfCalculatorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/remove-background': typeof ToolsRemoveBackgroundRoute
  '/tools/sip-calculator': typeof ToolsSipCalculatorRoute
  '/tools/text-on-photo': typeof ToolsTextOnPhotoRoute
  '/tools/time-zone-converter': typeof ToolsTimeZoneConverterRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/image-compressor'
    | '/image-to-pdf'
    | '/kb-resize-pixel'
    | '/pdf-to-image'
    | '/privacy'
    | '/qr-generator'
    | '/remove-background'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/tools/age-calculator'
    | '/tools/bmi-calculator'
    | '/tools/color-picker'
    | '/tools/crypto-converter'
    | '/tools/currency-converter'
    | '/tools/etsy-fee-calculator'
    | '/tools/fd-calculator'
    | '/tools/image-compressor'
    | '/tools/image-cropper'
    | '/tools/image-to-pdf'
    | '/tools/kb-converter'
    | '/tools/loan-emi-calculator'
    | '/tools/mortgage-calculator'
    | '/tools/number-converter'
    | '/tools/pdf-to-image'
    | '/tools/pincode-lookup'
    | '/tools/ppf-calculator'
    | '/tools/qr-generator'
    | '/tools/remove-background'
    | '/tools/sip-calculator'
    | '/tools/text-on-photo'
    | '/tools/time-zone-converter'
    | '/tools/unit-converter'
    | '/blog/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/image-compressor'
    | '/image-to-pdf'
    | '/kb-resize-pixel'
    | '/pdf-to-image'
    | '/privacy'
    | '/qr-generator'
    | '/remove-background'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/tools/age-calculator'
    | '/tools/bmi-calculator'
    | '/tools/color-picker'
    | '/tools/crypto-converter'
    | '/tools/currency-converter'
    | '/tools/etsy-fee-calculator'
    | '/tools/fd-calculator'
    | '/tools/image-compressor'
    | '/tools/image-cropper'
    | '/tools/image-to-pdf'
    | '/tools/kb-converter'
    | '/tools/loan-emi-calculator'
    | '/tools/mortgage-calculator'
    | '/tools/number-converter'
    | '/tools/pdf-to-image'
    | '/tools/pincode-lookup'
    | '/tools/ppf-calculator'
    | '/tools/qr-generator'
    | '/tools/remove-background'
    | '/tools/sip-calculator'
    | '/tools/text-on-photo'
    | '/tools/time-zone-converter'
    | '/tools/unit-converter'
    | '/blog'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/image-compressor'
    | '/image-to-pdf'
    | '/kb-resize-pixel'
    | '/pdf-to-image'
    | '/privacy'
    | '/qr-generator'
    | '/remove-background'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/tools/age-calculator'
    | '/tools/bmi-calculator'
    | '/tools/color-picker'
    | '/tools/crypto-converter'
    | '/tools/currency-converter'
    | '/tools/etsy-fee-calculator'
    | '/tools/fd-calculator'
    | '/tools/image-compressor'
    | '/tools/image-cropper'
    | '/tools/image-to-pdf'
    | '/tools/kb-converter'
    | '/tools/loan-emi-calculator'
    | '/tools/mortgage-calculator'
    | '/tools/number-converter'
    | '/tools/pdf-to-image'
    | '/tools/pincode-lookup'
    | '/tools/ppf-calculator'
    | '/tools/qr-generator'
    | '/tools/remove-background'
    | '/tools/sip-calculator'
    | '/tools/text-on-photo'
    | '/tools/time-zone-converter'
    | '/tools/unit-converter'
    | '/blog/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  KbResizePixelRoute: typeof KbResizePixelRoute
  PdfToImageRoute: typeof PdfToImageRoute
  PrivacyRoute: typeof PrivacyRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  RemoveBackgroundRoute: typeof RemoveBackgroundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ToolsAgeCalculatorRoute: typeof ToolsAgeCalculatorRoute
  ToolsBmiCalculatorRoute: typeof ToolsBmiCalculatorRoute
  ToolsColorPickerRoute: typeof ToolsColorPickerRoute
  ToolsCryptoConverterRoute: typeof ToolsCryptoConverterRoute
  ToolsCurrencyConverterRoute: typeof ToolsCurrencyConverterRoute
  ToolsEtsyFeeCalculatorRoute: typeof ToolsEtsyFeeCalculatorRoute
  ToolsFdCalculatorRoute: typeof ToolsFdCalculatorRoute
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsImageCropperRoute: typeof ToolsImageCropperRoute
  ToolsImageToPdfRoute: typeof ToolsImageToPdfRoute
  ToolsKbConverterRoute: typeof ToolsKbConverterRoute
  ToolsLoanEmiCalculatorRoute: typeof ToolsLoanEmiCalculatorRoute
  ToolsMortgageCalculatorRoute: typeof ToolsMortgageCalculatorRoute
  ToolsNumberConverterRoute: typeof ToolsNumberConverterRoute
  ToolsPdfToImageRoute: typeof ToolsPdfToImageRoute
  ToolsPincodeLookupRoute: typeof ToolsPincodeLookupRoute
  ToolsPpfCalculatorRoute: typeof ToolsPpfCalculatorRoute
  ToolsQrGeneratorRoute: typeof ToolsQrGeneratorRoute
  ToolsRemoveBackgroundRoute: typeof ToolsRemoveBackgroundRoute
  ToolsSipCalculatorRoute: typeof ToolsSipCalculatorRoute
  ToolsTextOnPhotoRoute: typeof ToolsTextOnPhotoRoute
  ToolsTimeZoneConverterRoute: typeof ToolsTimeZoneConverterRoute
  ToolsUnitConverterRoute: typeof ToolsUnitConverterRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remove-background': {
      id: '/remove-background'
      path: '/remove-background'
      fullPath: '/remove-background'
      preLoaderRoute: typeof RemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-image': {
      id: '/pdf-to-image'
      path: '/pdf-to-image'
      fullPath: '/pdf-to-image'
      preLoaderRoute: typeof PdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb-resize-pixel': {
      id: '/kb-resize-pixel'
      path: '/kb-resize-pixel'
      fullPath: '/kb-resize-pixel'
      preLoaderRoute: typeof KbResizePixelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/unit-converter': {
      id: '/tools/unit-converter'
      path: '/tools/unit-converter'
      fullPath: '/tools/unit-converter'
      preLoaderRoute: typeof ToolsUnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/time-zone-converter': {
      id: '/tools/time-zone-converter'
      path: '/tools/time-zone-converter'
      fullPath: '/tools/time-zone-converter'
      preLoaderRoute: typeof ToolsTimeZoneConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text-on-photo': {
      id: '/tools/text-on-photo'
      path: '/tools/text-on-photo'
      fullPath: '/tools/text-on-photo'
      preLoaderRoute: typeof ToolsTextOnPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sip-calculator': {
      id: '/tools/sip-calculator'
      path: '/tools/sip-calculator'
      fullPath: '/tools/sip-calculator'
      preLoaderRoute: typeof ToolsSipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/remove-background': {
      id: '/tools/remove-background'
      path: '/tools/remove-background'
      fullPath: '/tools/remove-background'
      preLoaderRoute: typeof ToolsRemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-generator': {
      id: '/tools/qr-generator'
      path: '/tools/qr-generator'
      fullPath: '/tools/qr-generator'
      preLoaderRoute: typeof ToolsQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ppf-calculator': {
      id: '/tools/ppf-calculator'
      path: '/tools/ppf-calculator'
      fullPath: '/tools/ppf-calculator'
      preLoaderRoute: typeof ToolsPpfCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pincode-lookup': {
      id: '/tools/pincode-lookup'
      path: '/tools/pincode-lookup'
      fullPath: '/tools/pincode-lookup'
      preLoaderRoute: typeof ToolsPincodeLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-image': {
      id: '/tools/pdf-to-image'
      path: '/tools/pdf-to-image'
      fullPath: '/tools/pdf-to-image'
      preLoaderRoute: typeof ToolsPdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/number-converter': {
      id: '/tools/number-converter'
      path: '/tools/number-converter'
      fullPath: '/tools/number-converter'
      preLoaderRoute: typeof ToolsNumberConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/mortgage-calculator': {
      id: '/tools/mortgage-calculator'
      path: '/tools/mortgage-calculator'
      fullPath: '/tools/mortgage-calculator'
      preLoaderRoute: typeof ToolsMortgageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/loan-emi-calculator': {
      id: '/tools/loan-emi-calculator'
      path: '/tools/loan-emi-calculator'
      fullPath: '/tools/loan-emi-calculator'
      preLoaderRoute: typeof ToolsLoanEmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/kb-converter': {
      id: '/tools/kb-converter'
      path: '/tools/kb-converter'
      fullPath: '/tools/kb-converter'
      preLoaderRoute: typeof ToolsKbConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-to-pdf': {
      id: '/tools/image-to-pdf'
      path: '/tools/image-to-pdf'
      fullPath: '/tools/image-to-pdf'
      preLoaderRoute: typeof ToolsImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-cropper': {
      id: '/tools/image-cropper'
      path: '/tools/image-cropper'
      fullPath: '/tools/image-cropper'
      preLoaderRoute: typeof ToolsImageCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/fd-calculator': {
      id: '/tools/fd-calculator'
      path: '/tools/fd-calculator'
      fullPath: '/tools/fd-calculator'
      preLoaderRoute: typeof ToolsFdCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/etsy-fee-calculator': {
      id: '/tools/etsy-fee-calculator'
      path: '/tools/etsy-fee-calculator'
      fullPath: '/tools/etsy-fee-calculator'
      preLoaderRoute: typeof ToolsEtsyFeeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/currency-converter': {
      id: '/tools/currency-converter'
      path: '/tools/currency-converter'
      fullPath: '/tools/currency-converter'
      preLoaderRoute: typeof ToolsCurrencyConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/crypto-converter': {
      id: '/tools/crypto-converter'
      path: '/tools/crypto-converter'
      fullPath: '/tools/crypto-converter'
      preLoaderRoute: typeof ToolsCryptoConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-picker': {
      id: '/tools/color-picker'
      path: '/tools/color-picker'
      fullPath: '/tools/color-picker'
      preLoaderRoute: typeof ToolsColorPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bmi-calculator': {
      id: '/tools/bmi-calculator'
      path: '/tools/bmi-calculator'
      fullPath: '/tools/bmi-calculator'
      preLoaderRoute: typeof ToolsBmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/age-calculator': {
      id: '/tools/age-calculator'
      path: '/tools/age-calculator'
      fullPath: '/tools/age-calculator'
      preLoaderRoute: typeof ToolsAgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  KbResizePixelRoute: KbResizePixelRoute,
  PdfToImageRoute: PdfToImageRoute,
  PrivacyRoute: PrivacyRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  RemoveBackgroundRoute: RemoveBackgroundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ToolsAgeCalculatorRoute: ToolsAgeCalculatorRoute,
  ToolsBmiCalculatorRoute: ToolsBmiCalculatorRoute,
  ToolsColorPickerRoute: ToolsColorPickerRoute,
  ToolsCryptoConverterRoute: ToolsCryptoConverterRoute,
  ToolsCurrencyConverterRoute: ToolsCurrencyConverterRoute,
  ToolsEtsyFeeCalculatorRoute: ToolsEtsyFeeCalculatorRoute,
  ToolsFdCalculatorRoute: ToolsFdCalculatorRoute,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsImageCropperRoute: ToolsImageCropperRoute,
  ToolsImageToPdfRoute: ToolsImageToPdfRoute,
  ToolsKbConverterRoute: ToolsKbConverterRoute,
  ToolsLoanEmiCalculatorRoute: ToolsLoanEmiCalculatorRoute,
  ToolsMortgageCalculatorRoute: ToolsMortgageCalculatorRoute,
  ToolsNumberConverterRoute: ToolsNumberConverterRoute,
  ToolsPdfToImageRoute: ToolsPdfToImageRoute,
  ToolsPincodeLookupRoute: ToolsPincodeLookupRoute,
  ToolsPpfCalculatorRoute: ToolsPpfCalculatorRoute,
  ToolsQrGeneratorRoute: ToolsQrGeneratorRoute,
  ToolsRemoveBackgroundRoute: ToolsRemoveBackgroundRoute,
  ToolsSipCalculatorRoute: ToolsSipCalculatorRoute,
  ToolsTextOnPhotoRoute: ToolsTextOnPhotoRoute,
  ToolsTimeZoneConverterRoute: ToolsTimeZoneConverterRoute,
  ToolsUnitConverterRoute: ToolsUnitConverterRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
